name: Deploy

# Controls when the action will run. 
# Triggers the workflow on push events but only for the master branch.
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: macos-11.3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Set build number
      run: /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $GITHUB_RUN_NUMBER" "IVDI/IVDI/Info.plist"

    - name: Build
      run: xcodebuild clean archive -sdk iphoneos -workspace IVDI/IVDI.xcworkspace -configuration "Release" -scheme "IVDI" -derivedDataPath "DerivedData" -archivePath "DerivedData/Archive/IVDI.xcarchive"
    
